### ISSUE TITLE
small reference for automated gh actions builds

### ISSUE THREAD

**Issue by jxsl13** [flathub/tw.ddnet.ddnet#111]
I did use this project in order to create a trusted ddnet client for our gctf league, big thanks for that.
For that I introduced a github workflow for building and releasing a flatpak package.
Maybe it helps you to get this automated, if you want:
```
on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:
name: Build
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-47
      options: --privileged
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: ddnet-19.0-linux.flatpak // bundle name - could be changed to automatically use the version if the branch is e.g. "v*"
        manifest-path: tw.ddnet.ddnet.yml
        upload-artifact: true
```
